### ISSUE TITLE
[Hang] Code hangs when choosing active project when two project starting with the same string are loaded

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1416]
### What Happened?

After adding another project to the foldermanager with "Load directory", while  documents were open and terminal pane visible, an attempt was made to set the new project as active. The popup closed and the open documents were closed but the active directory did not change.  A second attempt caused the interface to hang and required killing the process.

### Steps to Reproduce

1. Open two projects *starting with the same string* (e.g. `switchboard` and `switchboard-plug-xxx` and set one as active
2. Set the active project using the ChooseProjectButton
3. The interface hangs

### Expected Behavior

On loading a new project it should be able to be set as active without hanging the interface.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by jeremypw** [comment]
I now cannot reproduce this (but its happened a couple of times at least) so I may not have the sequence of steps exactly right.  Leaving open in case someone else experiences it and can reproduce.

**Comment by jeremypw** [comment]
Just had it again and this time was running under `gdb` - it seems that you need to have used "Close Other Folders" prior to loading the new project (?).  `gdb` output was `[Detaching after fork from child process 146835]` in an infinite loop.  Backtrace after interrupting was:
```
Thread 1 "io.elementary.c" received signal SIGINT, Interrupt.
arch_fork (ctid=0x7ffff2e5bf90) at ../sysdeps/unix/sysv/linux/arch-fork.h:52
52	../sysdeps/unix/sysv/linux/arch-fork.h: No such file or directory.
(gdb) bt
#0  arch_fork (ctid=0x7ffff2e5bf90) at ../sysdeps/unix/sysv/linux/arch-fork.h:52
#1  __GI__Fork () at ../sysdeps/nptl/_Fork.c:28
#2  0x00007ffff6aea98c in __libc_fork () at ./posix/fork.c:73
#3  0x00007ffff6d073b3 in  () at /lib/x86_64-linux-gnu/libvte-2.91.so.0
#4  0x00007ffff6d10b5e in  () at /lib/x86_64-linux-gnu/libvte-2.91.so.0
#5  0x00007ffff6cf22c9 in vte_terminal_spawn_sync () at /lib/x86_64-linux-gnu/libvte-2.91.so.0
#6  0x00005555555ffeea in code_terminal_spawn_shell
    (self=0x555555cff7b0, dir=0x5555564ddde0 "/home/jeremy/Elementary/switchboard/build")
    at ../src/Widgets/Terminal.vala:79
#7  0x00005555556000cb in code_terminal_change_location
    (self=0x555555cff7b0, dir=0x5555564ddde0 "/home/jeremy/Elementary/switchboard/build")
    at ../src/Widgets/Terminal.vala:97
#8  0x0000555555589009 in scratch_main_window_action_open_in_terminal
    (self=0x5555557f4370, action=0x555555971000, param=0x5555562df000) at ../src/MainWindow.vala:1315
#9  0x000055555557d7a3 in _scratch_main_window_action_open_in_terminal_gsimple_action_activate_callback
    (action=0x555555971000, parameter=0x5555562df000, self=0x5555557f4370) at ../src/MainWindow.vala:112
#10 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7c5fa8e in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x0000555555580624 in __lambda169_ (self=0x5555557f4370) at ../src/MainWindow.vala:627
#15 0x000055555558067d in ___lambda169__code_choose_project_button_project_chosen
    (_sender=0x5555559eab30, self=0x5555557f4370) at ../src/MainWindow.vala:622
#16 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00005555555d499f in _code_choose_project_button___lambda140_ (self=0x5555559eab30, row=0x55555621c9c0)
    at ../src/Widgets/ChooseProjectButton.vala:139
#21 0x00005555555d4a0a in __code_choose_project_button___lambda140__gtk_list_box_row_activated
    (_sender=0x5555559e7020, row=0x55555621c9c0, self=0x5555559eab30) at ../src/Widgets/ChooseProjectButton.vala:132
#22 0x00007ffff7c40745 in g_cclosure_marshal_VOID__OBJECTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7c5ec26 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff7c5fa8e in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00005555555d273d in __lambda132_ (_data29_=0x555555838ba0, child=0x55555621c9c0)
    at ../src/Widgets/ChooseProjectButton.vala:147
#26 0x00005555555d2781 in ___lambda132__gfunc (data=0x55555621c9c0, self=0x555555838ba0)
    at ../src/Widgets/ChooseProjectButton.vala:144
#27 0x00007ffff7eb5f80 in g_list_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00005555555d2892 in code_choose_project_button_set_active_path
    (self=0x5555559eab30, active_path=0x555555927eb0 "p\300\323UUU") at ../src/Widgets/ChooseProjectButton.vala:144
#29 0x00005555555d43d7 in _code_choose_project_button___lambda138_ (_data31_=0x555555803540)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../src/Widgets/ChooseProjectButton.vala:119
#30 0x00005555555d43fe in __code_choose_project_button___lambda138__g_object_notify
    (_sender=0x555555820e50, pspec=0x55555589ea10, self=0x555555803540)
    at ../src/Widgets/ChooseProjectButton.vala:118
#31 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff7c4c424 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff7c501fa in g_object_notify_by_pspec () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00005555555c5ee0 in scratch_services_git_manager_set_active_project_path
    (self=0x555555820e50, value=0x555555880a80 "/home/jeremy/Elementary/switchboard-plug-bluetooth")
    at ../src/Services/GitManager.vala:24
#38 0x00005555555d4947 in _code_choose_project_button___lambda140_ (self=0x5555559eab30, row=0x555555892f20)
    at ../src/Widgets/ChooseProjectButton.vala:137
#39 0x00005555555d4a0a in __code_choose_project_button___lambda140__gtk_list_box_row_activated
    (_sender=0x5555559e7020, row=0x555555892f20, self=0x5555559eab30) at ../src/Widgets/ChooseProjectButton.vala:132
#40 0x00007ffff7c40745 in g_cclosure_marshal_VOID__OBJECTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007ffff7c5f700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff7446a89 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007ffff75f0be5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007ffff7c5f700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff7407ffc in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff7c46866 in g_cclosure_marshal_VOID__BOXEDv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007ffff7c5f700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x00007ffff73ffacb in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007ffff740783b in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x00007ffff7408443 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#54 0x00007ffff73cef90 in gtk_event_controller_handle_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007ffff75a0045 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#56 0x00007ffff75e6eb8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#57 0x00007ffff7c5f700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#58 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#59 0x00007ffff75ae724 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x00007ffff7451680 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#61 0x00007ffff745252a in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#62 0x00007ffff7a96743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#63 0x00007ffff7acdf56 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#64 0x00007ffff7ebbd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#65 0x00007ffff7f11258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007ffff7eb93e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007ffff7d6dfb5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#68 0x000055555557c0c2 in scratch_application_main (args=0x7fffffffddd8, args_length1=1)
    at ../src/Application.vala:200
#69 0x000055555557c10f in main (argc=1, argv=0x7fffffffddd8) at ../src/Application.vala:199

```

**Comment by jeremypw** [comment]
Now got a hang with fewer steps and with the terminal pane closed but the backtrace is different:

```
0x00007ffff7ecee8d in g_sequence_iter_next () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff7ecee8d in g_sequence_iter_next () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff755d325 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff7585791 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff758790c in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff7591360 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff75865a3 in gtk_tree_view_collapse_row () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff7160b5b in  () at /lib/x86_64-linux-gnu/libgranite.so.6
#7  0x00007ffff7156c9c in  () at /lib/x86_64-linux-gnu/libgranite.so.6
#8  0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7c5de11 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff715102c in  () at /lib/x86_64-linux-gnu/libgranite.so.6
#13 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7c5de11 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff7c4c424 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff7c501fa in g_object_notify_by_pspec () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x0000555555598fe7 in scratch_folder_manager_file_view_collapse_other_projects
    (self=0x555555c1a410, keep_open_path=0x0) at ../src/FolderManager/FileView.vala:140
#24 0x00005555555804f5 in __lambda169_ (self=0x555555786370) at ../src/MainWindow.vala:623
#25 0x000055555558067d in ___lambda169__code_choose_project_button_project_chosen
    (_sender=0x5555559eab30, self=0x555555786370) at ../src/MainWindow.vala:622
#26 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00005555555d499f in _code_choose_project_button___lambda140_ (self=0x5555559eab30, row=0x555555d44db0)
    at ../src/Widgets/ChooseProjectButton.vala:139
#31 0x00005555555d4a0a in __code_choose_project_button___lambda140__gtk_list_box_row_activated
    (_sender=0x5555559e7020, row=0x555555d44db0, self=0x5555559eab30) at ../src/Widgets/ChooseProjectButton.vala:132
#32 0x00007ffff7c40745 in g_cclosure_marshal_VOID__OBJECTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff7c5ec26 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff7c5fa8e in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00005555555d273d in __lambda132_ (_data29_=0x55555585dee0, child=0x555555d44db0)
    at ../src/Widgets/ChooseProjectButton.vala:147
#36 0x00005555555d2781 in ___lambda132__gfunc (data=0x555555d44db0, self=0x55555585dee0)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../src/Widgets/ChooseProjectButton.vala:144
#37 0x00007ffff7eb5f80 in g_list_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00005555555d2892 in code_choose_project_button_set_active_path
    (self=0x5555559eab30, active_path=0x555556278880 "\200&\257UUU") at ../src/Widgets/ChooseProjectButton.vala:144
#39 0x00005555555d43d7 in _code_choose_project_button___lambda138_ (_data31_=0x555555803f40)
    at ../src/Widgets/ChooseProjectButton.vala:119
#40 0x00005555555d43fe in __code_choose_project_button___lambda138__g_object_notify
    (_sender=0x55555581e080, pspec=0x5555558c8a10, self=0x555555803f40)
    at ../src/Widgets/ChooseProjectButton.vala:118
#41 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff7c5f614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff7c4c424 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff7c501fa in g_object_notify_by_pspec () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00005555555c5ee0 in scratch_services_git_manager_set_active_project_path
    (self=0x55555581e080, value=0x555555d9ed10 "/home/jeremy/Elementary/files4")
    at ../src/Services/GitManager.vala:24
#48 0x00005555555d4947 in _code_choose_project_button___lambda140_ (self=0x5555559eab30, row=0x555555d44db0)
    at ../src/Widgets/ChooseProjectButton.vala:137
#49 0x00005555555d4a0a in __code_choose_project_button___lambda140__gtk_list_box_row_activated
    (_sender=0x5555559e7020, row=0x555555d44db0, self=0x5555559eab30) at ../src/Widgets/ChooseProjectButton.vala:132
#50 0x00007ffff7c40745 in g_cclosure_marshal_VOID__OBJECTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x00007ffff7c5f700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#52 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x00007ffff7c5f700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007ffff7c5fa8e in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x00005555555d3391 in _code_choose_project_button_project_row___lambda133_ (self=0x555555d44db0)
    at ../src/Widgets/ChooseProjectButton.vala:206
#56 0x00005555555d33c1 in __code_choose_project_button_project_row___lambda133__gtk_widget_button_release_event
    (_sender=0x555555d40c90, event=0x7fffd8004400, self=0x555555d44db0)
    at /home/jeremy/Elementary/code/build/ChooseProjectButton.c:911
#57 0x00007ffff75e5b77 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#58 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#59 0x00007ffff7c5dc36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#60 0x00007ffff7c5f026 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#61 0x00007ffff7c5f863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#62 0x00007ffff75ae724 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#63 0x00007ffff7451680 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#64 0x00007ffff745252a in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#65 0x00007ffff7a96743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#66 0x00007ffff7acdf56 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#67 0x00007ffff7ebbd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#68 0x00007ffff7f11258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#69 0x00007ffff7eb93e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#70 0x00007ffff7d6dfb5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#71 0x000055555557c0c2 in scratch_application_main (args=0x7fffffffddd8, args_length1=1)
    at ../src/Application.vala:200
#72 0x000055555557c10f in main (argc=1, argv=0x7fffffffddd8) at ../src/Application.vala:199
```
