### ISSUE TITLE
Folder Manager: Expanding folder with many files freezes interface

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#738]
I have searched open and closed issues for duplicates.

## Describe the bug
Expanding a folder that contains (e.g.) 1000 text files in the Sidebar folder manager freezes the interface for a long time (not determined).

### To Reproduce
1. Create a folder (root).
2. Create a subfolder in that folder
3. In the subfolder create about 1000 normal files.
4. Open the root folder in the folder manager
5. Press the expander against the subfolder
6. Nothing appears to happen and the interface freezes.  Code consumes a lot of CPU.

### Expected behavior
The folder expands within an acceptable time and the interface does not freeze.

### Logs
gdb  indicates that the SourceList is sorting while the interface is frozen.

```
gdb) next
141	in ../sysdeps/x86_64/multiarch/strlen-avx2.S
(gdb) next
143	in ../sysdeps/x86_64/multiarch/strlen-avx2.S
(gdb) next
144	in ../sysdeps/x86_64/multiarch/strlen-avx2.S
(gdb) next
145	in ../sysdeps/x86_64/multiarch/strlen-avx2.S
(gdb) next
146	in ../sysdeps/x86_64/multiarch/strlen-avx2.S
(gdb) bt
#0  0x00007ffff4cb060f in __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:146
#1  0x00007ffff7b2c444 in g_string_insert_len () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7b3c778 in g_utf8_collate_key_for_filename () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x000055555557da45 in scratch_folder_manager_file_compare (a=0x555556493520, b=0x55555642ac80)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/scratch-branches/forks/roymckenzie/code/src/FolderManager/File.vala:215
#4  0x0000555555588bcb in scratch_folder_manager_item_real_compare (base=0x555556242ca0, a=0x5555570503e0, b=0x555556f0feb0)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/scratch-branches/forks/roymckenzie/code/src/FolderManager/Item.vala:62
#5  0x00007ffff5f5b08b in granite_widgets_source_list_sortable_compare (self=0x555556242ca0, a=0x5555570503e0, b=0x555556f0feb0)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/granite-branches/granite/lib/Widgets/SourceList.vala:73
#6  0x00007ffff5f61f60 in granite_widgets_source_list_data_model_child_model_sort_func (self=0x5555559dc9c0, model=0x555555e9f290, a=0x7fffffffc700, b=0x7fffffffc3a0) at /media/jeremy/Shared/shared_data/Vala/Elementary/granite-branches/granite/lib/Widgets/SourceList.vala:1160
#7  0x00007ffff5f65dca in _granite_widgets_source_list_data_model_child_model_sort_func_gtk_tree_iter_compare_func (model=0x555555e9f290, a=0x7fffffffc700, b=0x7fffffffc3a0, self=0x5555559dc9c0) at SourceList.c:7486

```

## Platform Information
Elementary Juno unstable
 I'm using the latest version from git that I've manually compiled

**Comment by jeremypw** [comment]
Closing as I cannot now reproduce this issue as described above, in the current master version.
